linters-settings:
  errcheck:
    # [deprecated] comma-separated list of pairs of the form pkg:regex
    # the regex is used to ignore names within pkg. (default "fmt:.*").
    ignore: fmt:.*,io/ioutil:^Read.*,io:Close,:Delete
  lll:
    line-length: 170
  funlen:
    lines: 100
    statements: 80

run:
  timeout: 10m
  issues-exit-code: 1
  skip-files:
    - ".*_test.go$"
    - ".*generate.*.go$"
  skip-dirs:
    - "client/clienttest"

linters:
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - errorlint
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
